### ISSUE TITLE
Free Play text to LED Ticker on Rootage

### ISSUE THREAD

**Issue by tobeannouncd** [mon/BemaniPatcher#100]
When I enable this option on a dll for 2019-09-02, the free play text removed but there is no LED Ticker text.

**Comment by mirrornoir** [comment]
More info copy pasted thanks to RHKirby and mono-type on the forums.

> I believe this is the fixed version of the "Free play text to LED ticker (Bottom Right)" hex edit: `106F9F: 35 2F 35 00 -> 59 61 03 03`

> I can also confirm this is the correct hex edit. Turns out mon's online patcher has the wrong values; `D9 68 44 02` instead of the correct `59 61 03 03`.

**Comment by mon** [comment]
@mirrornoir I am going to be low-contact for the next 2 weeks, if you can make a PR with that fix I can merge it to the live site almost immediately

**Comment by mirrornoir** [comment]
@mon, I made a pull request https://github.com/mon/BemaniPatcher/pull/101. Thanks for getting me out of my comfort zone, this was my first PR.

**Comment by mon** [comment]
Fixed via #101
