### ISSUE TITLE
some address for sdvx iv KFC-2018011600

### ISSUE THREAD

**Issue by knuckleslee** [mon/BemaniPatcher#15]
Celysus#7845 post these code on discord:
NOTE: i don't ~really~ know how the hacks work i just copied the new data from that other guy's guide, and it all seems to work just fine, but who knows if i did it right

Auto Event Mode Toggled (Freeplay (Coin Options) must be "ON" for this to work efficiently)
0x1977D3 : 00 > 01

Song & Difficulty Unlock
0x1531F2 E8 09 42 02 -> B8 0D 00 00 (Difficulty Unlock)
0x1B5F39 8B 44 24 20 E8 3E EB FF FF -> B8 03 00 00 00 90 90 90 90 (Song Unlock)

2 Song Safe
0x172CDB: 32 C0 -> B0 01

Premium Free Hack
0x1CC10F: 00 -> 02

0x1CC2D6: 8B 83 64 10 00 00 8D 48 01 83 F9 04 56 57 7F 52 -> B8 01 00 00 00 89 83 64 10 00 00 90 56 57 90 90

NOTE: Combine with 2 Song Safe Hex above for full effect

Safe Banner Removal
0x2EB3EC: 73 -> 00

**Comment by mon** [comment]
Thanks
