### ISSUE TITLE
BISTROVER: "Hide all bottom text" writes over raw text

### ISSUE THREAD

**Issue by Silverdesu** [mon/BemaniPatcher#191]
The patch as-is:
- directly overwrites the text for all bottom tooltips, which also overwrites the "FREE PLAY" text in coin options
- does not feature freeplay text to LED ticker as noted by tooltip (unless the tooltip is saying that LED ticker _should still display if anyone finds the patch_), since all it does is overwrite the relevant text from `0x95EA70` to `0x95EB8F`

Its description and tooltip should be edited to reflect this, but honestly I don't think it should be used at all since it directly writes over raw text (instead of redirecting like the Heroic Verse patches do)

**Comment by mon** [comment]
If it's so scuffed, submit a PR to remove it and I will accept

**Comment by Silverdesu** [comment]
submitted as pull request #192

**Comment by mon** [comment]
Cheers!
