### ISSUE TITLE
Force Background Judgement DDR A20+

### ISSUE THREAD

**Issue by vlsaurus1** [mon/BemaniPatcher#267]
I'm really sorry for issue spam, but am reporting issues as I see them. 

Setting the "force background judgement" setting doesn't do anything. I can kinda get around this for now by enabling it in the asphyxia webui.

I realize that this is a very recent patcher, so there are still kinks that need to be worked out. Again, I'm just reporting issues as I see them!

**Comment by mon** [comment]
You're welcome to keep posting issues, just keep in mind that I do not make patches, they are user submitted. If they don't work, it's probably better to find who made them (if possible) and ask for a fix that way.

**Comment by vlsaurus1** [comment]
alright thank you!

**Comment by wz18207** [comment]
asphyxia doesnt support ddr currently.
well Force game darkest background means force gameplay filter in darkest state in dll edit without depending on network.
useful for research only

**Comment by mon** [comment]
I believe this has been fixed in #278, with thanks to drmext
