### ISSUE TITLE
[DDR X3] Cannot get past the paseli description on the entry screen with the timer freeze enabled.

### ISSUE THREAD

**Issue by vlsaurus1** [mon/BemaniPatcher#282]
I can't get past this screen with the timer freeze enabled. It does this because the countdown has to start before you can hit start. Is it possible that you (drmext) may be able to fix this?

Cannot get past this screen.
![20220603_0](https://user-images.githubusercontent.com/62578321/171768354-68924ca5-8564-4c47-a591-fb34cfd3866c.png)

Thank you!

**Comment by mon** [comment]
@drmext

**Comment by mon** [comment]
Fixed in #283
