### ISSUE TITLE
oof KFC2018-06-13 doesn't work any more

### ISSUE THREAD

**Issue by camprevail** [mon/BemaniPatcher#30]
Worked before the last update... The offsets are the same

**Comment by mon** [comment]
That isn't even in the list of DLLs. Chance that a new hex edit no longer matches your out of date dll?

Feel free to email it to me for further analysis.

**Comment by ahmedgamedev** [comment]
can i have that

**Comment by camprevail** [comment]
Yeah looks like it. One of the edits added after pfree broke compatibility. No worries, I have the previous version of the last commit saved, you can close the issue.

**Comment by mon** [comment]
If you insist
