### ISSUE TITLE
The "Force Extra Stage/Extra Encore Stage" doesn't work for DDR A

### ISSUE THREAD

**Issue by TrialMacameau** [mon/BemaniPatcher#40]
I tried a song with that checked out and it only causes a crash.

Possible solution I did was change the Song Stage to 1 and it didn't work. (Crash)

And I'm currently playing the Dumped DDR A version 2018-04-23 with the SpiceTool.

**Comment by mon** [comment]
@Poliwrath any ideas?

**Comment by Poliwrath** [comment]
Oh uh, according to the the DDR A modding discord this patch doesn't work, but someone should soon be making a PR with a working hex edit

Should I DM you a invite to the discord, mon? (I feel jamaican now o_o)

**Comment by mon** [comment]
@Poliwrath sure, though expect me to just mute all the channels unless I'm pinged

**Comment by TrialMacameau** [comment]
I see it has been fixed and it works perfectly now so I'm gonna close this issue. Thanks a lot for fixing it o/
